### PR TITLE
rubocop: Style/SafeNavigation

### PR DESCRIPTION
**Pull request by mlinksva**
🙇 👮

### CODE REVIEW

**Comment by mlinksva** [comment]
Hmm, failing under ruby 2.5 due to

> Your RubyGems version (2.7.6.3) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`

**Comment by mlinksva** [comment]
Hmm2, now I don't know why rubocop has a zillion complaints under ruby 2.5.

For now I've just disabled Style/SafeNavigation in #615

**Comment by mlinksva** [comment]
Closing in preference to #616

**Comment by Learningtosurvive** [comment]
honestly, I really need some help with this cause I’m a little behind the
ears if I am I said I’m trying to understand a little bit more about the
coding and if you don’t mind helping, I’d appreciate it

**Pull request closed without merging**
